/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authOnboardingRouteImport } from './routes/(auth)/onboarding'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authSignupTermsRouteImport } from './routes/(auth)/signup/terms'
import { Route as authSignupPasswordRouteImport } from './routes/(auth)/signup/password'
import { Route as authSignupEmailVerificationRouteImport } from './routes/(auth)/signup/emailVerification'
import { Route as authSignupEmailRouteImport } from './routes/(auth)/signup/email'
import { Route as authOnboardingProfileRouteImport } from './routes/(auth)/onboarding/profile'
import { Route as authOnboardingIntroRouteImport } from './routes/(auth)/onboarding/intro'
import { Route as authOnboardingCategoryRouteImport } from './routes/(auth)/onboarding/category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authOnboardingRoute = authOnboardingRouteImport.update({
  id: '/(auth)/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupTermsRoute = authSignupTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => authSignupRoute,
} as any)
const authSignupPasswordRoute = authSignupPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => authSignupRoute,
} as any)
const authSignupEmailVerificationRoute =
  authSignupEmailVerificationRouteImport.update({
    id: '/emailVerification',
    path: '/emailVerification',
    getParentRoute: () => authSignupRoute,
  } as any)
const authSignupEmailRoute = authSignupEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => authSignupRoute,
} as any)
const authOnboardingProfileRoute = authOnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => authOnboardingRoute,
} as any)
const authOnboardingIntroRoute = authOnboardingIntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => authOnboardingRoute,
} as any)
const authOnboardingCategoryRoute = authOnboardingCategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => authOnboardingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/onboarding': typeof authOnboardingRouteWithChildren
  '/signup': typeof authSignupRouteWithChildren
  '/onboarding/category': typeof authOnboardingCategoryRoute
  '/onboarding/intro': typeof authOnboardingIntroRoute
  '/onboarding/profile': typeof authOnboardingProfileRoute
  '/signup/email': typeof authSignupEmailRoute
  '/signup/emailVerification': typeof authSignupEmailVerificationRoute
  '/signup/password': typeof authSignupPasswordRoute
  '/signup/terms': typeof authSignupTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/onboarding': typeof authOnboardingRouteWithChildren
  '/signup': typeof authSignupRouteWithChildren
  '/onboarding/category': typeof authOnboardingCategoryRoute
  '/onboarding/intro': typeof authOnboardingIntroRoute
  '/onboarding/profile': typeof authOnboardingProfileRoute
  '/signup/email': typeof authSignupEmailRoute
  '/signup/emailVerification': typeof authSignupEmailVerificationRoute
  '/signup/password': typeof authSignupPasswordRoute
  '/signup/terms': typeof authSignupTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/onboarding': typeof authOnboardingRouteWithChildren
  '/(auth)/signup': typeof authSignupRouteWithChildren
  '/(auth)/onboarding/category': typeof authOnboardingCategoryRoute
  '/(auth)/onboarding/intro': typeof authOnboardingIntroRoute
  '/(auth)/onboarding/profile': typeof authOnboardingProfileRoute
  '/(auth)/signup/email': typeof authSignupEmailRoute
  '/(auth)/signup/emailVerification': typeof authSignupEmailVerificationRoute
  '/(auth)/signup/password': typeof authSignupPasswordRoute
  '/(auth)/signup/terms': typeof authSignupTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/onboarding/category'
    | '/onboarding/intro'
    | '/onboarding/profile'
    | '/signup/email'
    | '/signup/emailVerification'
    | '/signup/password'
    | '/signup/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/onboarding/category'
    | '/onboarding/intro'
    | '/onboarding/profile'
    | '/signup/email'
    | '/signup/emailVerification'
    | '/signup/password'
    | '/signup/terms'
  id:
    | '__root__'
    | '/'
    | '/(auth)/login'
    | '/(auth)/onboarding'
    | '/(auth)/signup'
    | '/(auth)/onboarding/category'
    | '/(auth)/onboarding/intro'
    | '/(auth)/onboarding/profile'
    | '/(auth)/signup/email'
    | '/(auth)/signup/emailVerification'
    | '/(auth)/signup/password'
    | '/(auth)/signup/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  authOnboardingRoute: typeof authOnboardingRouteWithChildren
  authSignupRoute: typeof authSignupRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/onboarding': {
      id: '/(auth)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup/terms': {
      id: '/(auth)/signup/terms'
      path: '/terms'
      fullPath: '/signup/terms'
      preLoaderRoute: typeof authSignupTermsRouteImport
      parentRoute: typeof authSignupRoute
    }
    '/(auth)/signup/password': {
      id: '/(auth)/signup/password'
      path: '/password'
      fullPath: '/signup/password'
      preLoaderRoute: typeof authSignupPasswordRouteImport
      parentRoute: typeof authSignupRoute
    }
    '/(auth)/signup/emailVerification': {
      id: '/(auth)/signup/emailVerification'
      path: '/emailVerification'
      fullPath: '/signup/emailVerification'
      preLoaderRoute: typeof authSignupEmailVerificationRouteImport
      parentRoute: typeof authSignupRoute
    }
    '/(auth)/signup/email': {
      id: '/(auth)/signup/email'
      path: '/email'
      fullPath: '/signup/email'
      preLoaderRoute: typeof authSignupEmailRouteImport
      parentRoute: typeof authSignupRoute
    }
    '/(auth)/onboarding/profile': {
      id: '/(auth)/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof authOnboardingProfileRouteImport
      parentRoute: typeof authOnboardingRoute
    }
    '/(auth)/onboarding/intro': {
      id: '/(auth)/onboarding/intro'
      path: '/intro'
      fullPath: '/onboarding/intro'
      preLoaderRoute: typeof authOnboardingIntroRouteImport
      parentRoute: typeof authOnboardingRoute
    }
    '/(auth)/onboarding/category': {
      id: '/(auth)/onboarding/category'
      path: '/category'
      fullPath: '/onboarding/category'
      preLoaderRoute: typeof authOnboardingCategoryRouteImport
      parentRoute: typeof authOnboardingRoute
    }
  }
}

interface authOnboardingRouteChildren {
  authOnboardingCategoryRoute: typeof authOnboardingCategoryRoute
  authOnboardingIntroRoute: typeof authOnboardingIntroRoute
  authOnboardingProfileRoute: typeof authOnboardingProfileRoute
}

const authOnboardingRouteChildren: authOnboardingRouteChildren = {
  authOnboardingCategoryRoute: authOnboardingCategoryRoute,
  authOnboardingIntroRoute: authOnboardingIntroRoute,
  authOnboardingProfileRoute: authOnboardingProfileRoute,
}

const authOnboardingRouteWithChildren = authOnboardingRoute._addFileChildren(
  authOnboardingRouteChildren,
)

interface authSignupRouteChildren {
  authSignupEmailRoute: typeof authSignupEmailRoute
  authSignupEmailVerificationRoute: typeof authSignupEmailVerificationRoute
  authSignupPasswordRoute: typeof authSignupPasswordRoute
  authSignupTermsRoute: typeof authSignupTermsRoute
}

const authSignupRouteChildren: authSignupRouteChildren = {
  authSignupEmailRoute: authSignupEmailRoute,
  authSignupEmailVerificationRoute: authSignupEmailVerificationRoute,
  authSignupPasswordRoute: authSignupPasswordRoute,
  authSignupTermsRoute: authSignupTermsRoute,
}

const authSignupRouteWithChildren = authSignupRoute._addFileChildren(
  authSignupRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  authOnboardingRoute: authOnboardingRouteWithChildren,
  authSignupRoute: authSignupRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
